/** @type { importCharacterConfig['card'] } */
const cards = {
	hejin_tiegu: {
		fullskin: true,
		type: "equip",
		subtype: "equip2",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "heart",
		yitiNumber: 1,
		chineseName: "合金铁骨",
		skills: ["hejin_tiegu_skill"],
		ai: { basic: { equipValue: 5.5 } },
	},

	fu_xinzang: {
		fullskin: true,
		type: "equip",
		subtype: "equip2",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "heart",
		yitiNumber: 2,
		chineseName: "副心脏",
		skills: ["fu_xinzang_skill"],
		ai: { basic: { equipValue: 7 } },
	},

	huoxue_beng: {
		fullskin: true,
		type: "equip",
		subtype: "equip2",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "heart",
		yitiNumber: 3,
		chineseName: "活血泵",
		skills: ["huoxue_beng_skill"],
		ai: { basic: { equipValue: 6 } },
	},

	pixia_hujia: {
		fullskin: true,
		type: "equip",
		subtype: "equip2",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "heart",
		yitiNumber: 4,
		chineseName: "皮下护甲",
		skills: ["pixia_hujia_skill"],
		ai: { basic: { equipValue: 5.5 } },
	},

	tengtong_bianjiqi: {
		fullskin: true,
		type: "equip",
		subtype: "equip2",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "heart",
		yitiNumber: 5,
		chineseName: "疼痛编辑器",
		skills: ["tengtong_bianjiqi_skill"],
		ai: { basic: { equipValue: 5.5 } },
	},

	tengtong_zhihuan: {
		fullskin: true,
		type: "equip",
		subtype: "equip2",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "heart",
		yitiNumber: 6,
		chineseName: "疼痛置换",
		skills: ["tengtong_zhihuan_skill"],
		ai: { basic: { equipValue: 7 } },
	},

	guangxue_micai: {
		fullskin: true,
		type: "equip",
		subtype: "equip2",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "heart",
		yitiNumber: 7,
		chineseName: "光学迷彩",
		skills: ["guangxue_micai_skill"],
		ai: { basic: { equipValue: 6 } },
	},

	zhimi_gusui: {
		fullskin: true,
		type: "equip",
		subtype: "equip2",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "heart",
		yitiNumber: 8,
		chineseName: "致密骨髓",
		skills: ["zhimi_gusui_skill"],
		ai: { basic: { equipValue: 6 } },
	},

	fangsheng_guanjie: {
		fullskin: true,
		type: "equip",
		subtype: "equip2",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "heart",
		yitiNumber: 9,
		chineseName: "仿生关节",
		skills: ["fangsheng_guanjie_skill"],
		ai: { basic: { equipValue: 6 } },
	},

	shengwu_suliao_xueguan: {
		fullskin: true,
		type: "equip",
		subtype: "equip2",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "heart",
		yitiNumber: 10,
		chineseName: "生物塑料血管",
		skills: ["shengwu_suliao_xueguan_skill"],
		ai: { basic: { equipValue: 5.5 } },
	},

	neicun_peiping: {
		fullskin: true,
		type: "equip",
		subtype: "equip2",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "heart",
		yitiNumber: 11,
		chineseName: "内存配平",
		skills: ["neicun_peiping_skill"],
		ai: { basic: { equipValue: 5.5 } },
	},

	zhineng_sharuan: {
		fullskin: true,
		type: "equip",
		subtype: "equip2",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "heart",
		yitiNumber: 12,
		chineseName: "智能杀软",
		skills: ["zhineng_sharuan_skill"],
		ai: { basic: { equipValue: 5.5 } },
	},

	tezheng_tongbu_lianban: {
		fullskin: true,
		type: "equip",
		subtype: "equip2",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "heart",
		yitiNumber: 13,
		chineseName: "特征同步脸板",
		skills: ["tezheng_tongbu_lianban_skill"],
		ai: { basic: { equipValue: 6.5 } },
	},
};

export default cards;
