/** @type { importCharacterConfig['card'] } */
const cards = {
	mituan_rendai: {
		fullskin: true,
		type: "equip",
		subtype: "equip3_4",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "club",
		yitiNumber: 1,
		chineseName: "灭团韧带",
		distance: { globalFrom: -2 },
		skills: [],
		ai: { basic: { equipValue: 5 } },
	},

	qilusi_yiyan: {
		fullskin: true,
		type: "equip",
		subtype: "equip3_4",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "club",
		yitiNumber: 2,
		chineseName: "歧路司义眼",
		distance: { globalFrom: 0 },
		skills: ["qilusi_skill1"],
		ai: { basic: { equipValue: 7 } },
	},

	huaibu_jiagu: {
		fullskin: true,
		type: "equip",
		subtype: "equip3_4",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "club",
		yitiNumber: 3,
		chineseName: "踝部加固",
		distance: { globalFrom: -1 },
		skills: ["huaibu_jiagu_skill"],
		ai: { basic: { equipValue: 5.5 } },
	},

	qianghua_jijian: {
		fullskin: true,
		type: "equip",
		subtype: "equip3_4",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "club",
		yitiNumber: 4,
		chineseName: "强化肌腱",
		distance: { globalFrom: -1 },
		skills: ["qianghua_jijian_skill"],
		ai: { basic: { equipValue: 5.5 } },
	},

	fanying_tiaoxieqi: {
		fullskin: true,
		type: "equip",
		subtype: "equip3_4",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "club",
		yitiNumber: 5,
		chineseName: "反应调谐器",
		distance: { globalFrom: -1 },
		skills: ["fanying_tiaoxieqi_skill"],
		ai: { basic: { equipValue: 5.5 } },
	},

	kelunqikefu: {
		fullskin: true,
		type: "equip",
		subtype: "equip3_4",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "club",
		yitiNumber: 6,
		chineseName: "克伦齐科夫",
		distance: { globalFrom: -1 },
		skills: ["kelunqikefu_skill"],
		ai: { basic: { equipValue: 6 } },
	},

	tuchu_jiasuqi: {
		fullskin: true,
		type: "equip",
		subtype: "equip3_4",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "club",
		yitiNumber: 7,
		chineseName: "突触加速器",
		distance: { globalFrom: -1 },
		skills: ["tuchu_jiasuqi_skill"],
		ai: { basic: { equipValue: 6 } },
	},

	shenshangxiansu_zengqiangjian: {
		fullskin: true,
		type: "equip",
		subtype: "equip3_4",
		yiti: true,
		recastable: true,
		enable: false,
		cardcolor: "club",
		yitiNumber: 8,
		chineseName: "肾上腺素增强件",
		distance: { globalFrom: -1 },
		skills: ["shenshangxiansu_zengqiangjian_skill"],
		ai: { basic: { equipValue: 6 } },
	},
};

export default cards;
